### ISSUE TITLE
Why not just add these to Thomas's repo?

### ISSUE THREAD

**Issue by jdegand** [dalenguyen/angular-challenges#3]
You are always gonna be in the shadow of the original repo.  I understand the desire for more autonomy, but if you want to reach more people, it would be better to just contribute to the other repo.

If you want to stay separate, the niche you could explore is older style Angular.  Angular 9 actually is the most used version.  The other repo is heavily skewed to newer Angular features.  I can add the repo to Awesome Angular and see if you can garner more traffic.

**Comment by dalenguyen** [comment]
Thanks, @jdegand for your suggestions. I was planning to do add some to Thomas anyway. Just didn't had the chance to do it yet :D 

I would keep this one as testing ground for newer versions / my own experiments since I also want to keep moving forward. Traffic is not important for this one.
